security.ignored: /console/**

spring.h2.console:
  enabled: true
  path: /console

server:
  port: 8443
  
spring:
  application:
    name: auth
  redis:
    host: redis
    port: 6379

#eureka:
#  client:
#    service-url:
#      discovery1:8761, discovery2:8762